### ISSUE TITLE
Clickiness of output signals

### ISSUE THREAD

**Issue by faroit** [interactiveaudiolab/nussl#115]
Hi, I just listened to some of your sisec submissions and found that a few methods have some windowing artifacts (clicks of multiples of 1024 samples).

I did not evaluate this systematically but I found this in 2DFT and HPLP. Just wanted let you know if this is maybe caused by a bug in the nussl synthesis module?

![screen shot 2018-05-29 at 15 23 56](https://user-images.githubusercontent.com/72940/40661961-4f31f9ec-6355-11e8-8978-ac8d39d9a2c6.png)

**Comment by faroit** [comment]
@ethman when we met at ISMIR, you told me that this bug has been addressed. 
Now, I am interested in checking some of my internal STFT implementations I use to see if they are suspect to the same problems.

Can you point me to the commit that solved the issue and maybe give some more information about possible unit tests to catch these error in STFT implementations?

**Comment by pseeth** [comment]
Hi @faroit, we've put a fix for this into one of the branches which we'll hopefully be merging into master soon. Here's what changed:

https://github.com/interactiveaudiolab/nussl/commit/4294c68c9127cdcf3f26ef0bd7c6277fd58ae7b7

Haven't written a test yet but this is the fix! The error happens when you apply masking before inverting an STFT. So you won't catch with an stft followed by an istft (which gives very low reconstruction error), but only when you apply masking after the stft and then invert the masked stft. Thanks @fpishdadian for figuring this out! When this is merged and a test is written, we'll close this bug.

**Comment by pseeth** [comment]
We switched entirely to the scipy stft in the latest version to circumvent this issue.
