### ISSUE TITLE
Duet IndexError when given identical channels

### ISSUE THREAD

**Issue by maxrmorrison** [interactiveaudiolab/nussl#127]
#### Description
Passing a mixture of 2 sources with identical l/r channels to `Duet` produces an `IndexError` at line 349 in `_compute_masks`.

#### Steps/Code to Reproduce

``` python
    flute = nussl.AudioSignal('flute.wav')
    drums = nussl.AudioSignal('drums.wav')

    if flute.signal_length > drums.signal_length:
        flute.truncate_samples(drums.signal_length)
    elif flute.signal_length < drums.signal_length:
        drums.truncate_samples(flute.signal_length)

    signal = np.repeat((flute + drums).audio_data, 2, axis=0)
    signal = nussl.AudioSignal(audio_data_array=signal)

    algo = nussl.Duet(signal, num_sources=2)
    algo()
```

#### Expected Results
No error is thrown or a `ValueError` is thrown with a description that the signal is incompatible with the algorithm

#### Actual Results
```
Traceback (most recent call last):
  File "duet.py", line 19, in <module>
    algo()
  File "C:\Users\maxrm\Anaconda3\envs\nussl\lib\site-packages\nussl\separation\separation_base.py", line 158, in __call__
    return self.run()
  File "C:\Users\maxrm\Anaconda3\envs\nussl\lib\site-packages\nussl\separation\duet.py", line 174, in run
    computed_masks = self._compute_masks()
  File "C:\Users\maxrm\Anaconda3\envs\nussl\lib\site-packages\nussl\separation\duet.py", line 349, in _compute_masks
    phase = np.exp(-1j * self.frequency_matrix * self.delay_peak[i])
IndexError: index 1 is out of bounds for axis 0 with size 1
```

#### Versions

```
Windows-10-10.0.17134
('Python', '2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:09) [MSC v.1500 64 bit (AMD64)]')
('NumPy', '1.15.2')
('SciPy', '1.1.0')
('librosa', '0.6.2')
('nussl', '0.1.6')
```

**Comment by radkoff** [comment]
I'm getting this even when the channels are different

```
File "/Users/radkoff/anaconda3/envs/nussl/lib/python2.7/site-packages/nussl/separation/duet.py", line 349, in _compute_masks
    phase = np.exp(-1j * self.frequency_matrix * self.delay_peak[i])
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Same size, different values
```
>>> time_series_stereo[0].shape
(6630912,)
>>> time_series_stereo[1].shape
(6630912,)
>>> time_series_stereo[0][4000]
-1.1044885e-05
>>> time_series_stereo[1][4000]
-4.0526193e-05
```

Mac os
python                    2.7.15
nussl                     0.1.6 
numpy                     1.15.4
vamp                      1.1.0
librosa                   0.6.2

**Comment by pseeth** [comment]
Fixed this by adjusting the default peak_threshold down from 0.2 to 0.0. The threshold was set too high, filtering out some of the peaks even if they do exist. Haven't merged into master yet, but here it is:

https://github.com/interactiveaudiolab/nussl/commit/e8261ca29e9b68b577cd3abcf3d530c16a90ee77

**Comment by ethman** [comment]
Thanks for figuring this out prem!

I'm not convinced that just changing the default value is the right move in this situation. For one, it changes the behavior of the algorithm for those who aren't taking the time to understand and change these settings (and we'll have to rerender our benchmark file for DUET). 

But more importantly, I think the real issue is that the error message is too oblique to parse usefully. If the error message read `Couldn't find peaks in the attenuation/delay histogram! Try changing peak_threshold.` perhaps these smart `nussl`ers would have enough information to debug their algorithms themselves. 

So, I'm advocating for keeping the default value as is, and rather detecting this case and still crashing, just with a better error message.
