### ISSUE TITLE
Add PyTorch to requirements.txt

### ISSUE THREAD

**Issue by maxrmorrison** [interactiveaudiolab/nussl#130]
PyTorch is not currently installed with the provided `requirements.txt`. It would be great if this could be included in the installation. A cross-platform install of `torch` (and `torchvision`) can be done by adding these 3 lines to `requirements.txt`:
```
torch==0.4.1; sys_platform == 'linux'
torch==0.4.1; sys_platform == 'darwin'
http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl; sys_platform == 'win32'
torchvision==0.2.1
```

Hopefully PyTorch will decide to put their wheels for Windows up on pip some day.

**Comment by ethman** [comment]
I initially resisted making pytorch an official dependency because of this yuckiness, esp wrt users who don't want to use any of the deep stuff in nussl and want to keep it light. Thus there are workarounds like the dummy `DeepClustering` class in `separation/__init__.py`  (https://github.com/interactiveaudiolab/nussl/blob/d3f1dbfccfda3a068cf7da4f97be636c423d9687/nussl/separation/__init__.py#L53), which is an unsustainable solution.

Does anyone think there's a reason not to just bite the bullet an fully onboard pytorch? @pseeth @nathanshelly

**Comment by nathanshelly** [comment]
I would vote for making PyTorch an official dependency, especially given Max's cross-platform fix here.

**Comment by pseeth** [comment]
I agree. I think PyTorch is eventually gonna end up in a lot of places in nussl.

**Comment by pseeth** [comment]
And so it has!
