### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by radkoff** [interactiveaudiolab/nussl#132]
Hello, thanks for making nussl open-source! I was wondering if there's any timeline for making it compatible with python 3. Or, if you think it's easy enough for an individual to handle on their own.

**Comment by pseeth** [comment]
Thanks for using nussl! We will be migrating nussl to Python 3 soon-ish. We have a branch (train: https://github.com/interactiveaudiolab/nussl/tree/train) that will have some other features as well but is also completely Python 3 as of now. Since numpy and scipy are ditching Python 2 support entirely by 2020, moving to Python 3 is pretty important for us. We haven't merged it yet into master and done a version bump or anything (and also that branch is experimental and doesn't have enough test coverage yet) but we will put a timeline together soon.

**Comment by ethman** [comment]
Hey! I think Prem said it all mostly. It's definitely on our radar and will be in our next pip, but for now github is your only option. I'll also add that it would be great to have someone testing out python 3 version of nussl and provide feedback if necessary. Happy separating!

**Comment by radkoff** [comment]
Awesome, thanks! Yeah, I may take a peak at that branch, and if I notice anything broken I'll message you or open an issue

**Comment by faroit** [comment]
Python 2.7 will be unmaintained by January 1, 2020. Do you plan to fully move to python 3?

**Comment by ethman** [comment]
Hi all, we've been busy working behind the scenes on some new big improvements to nussl. This includes a migration to python 3. We're hoping to have everything clean and wrapped up well before the January 1, 2020 deadline and we'll make an announcement when we've migrated everything into master and made a new pip version.

**Comment by faroit** [comment]
Yay, thats great to hear. :+1:

**Comment by pseeth** [comment]
nussl is now completely compatible with Python 3. Happy separating!
