### ISSUE TITLE
Allow algorithms to accept numpy arrays instead of AudioSignals

### ISSUE THREAD

**Issue by interactiveaudiolab** [interactiveaudiolab/nussl#57]

**Comment by ethman** [comment]
I've been thinking a lot about this, and I think this would muddy up the interface for a lot of the algorithms. This is due to the fact that python isn't strongly typed, so we can't overload the constructor, meaning that we'd have to do a lot of extra logic at the beginning of every separation base constructor just to get everything set up correctly. Whereas for the user, it's one more line of code before the constructor. I see this as a whole lot of work just to save one line of code for the user. 

Additionally, all SeparationBase algorithms _should_ be returning AudioSignal objects and it seems imbalanced to input an array and output a completely different object.

I'll leave this open for now to see what other people's thoughts are.

**Comment by pseeth** [comment]
I think this was mostly a workaround from before when the AudioSignal interface wasn't as good as the librosa interface (this is down to the duration/offset arguments that were in librosa but not in AudioSignal). Now that the interfaces are basically the same, it's fine the way it is. I'm fine closing this as "wontfix".

**Comment by ethman** [comment]
Sounds good.
