### ISSUE TITLE
signal_length and signal_starting_position

### ISSUE THREAD

**Issue by pseeth** [interactiveaudiolab/nussl#61]
These are hard to use. First, they take input as an int, in terms of samples, rather than seconds. Second, the variable names are pretty verbose - how about offset and duration instead? Finally, it throws an error if signal_starting_position >= signal_length. So if I wanted 30 seconds of audio starting at 30 seconds into the audio file, how do I do that?

**Comment by ethman** [comment]
I've got a fix. I've got a few things on my plate before I can test and push it, but it should be in the nussl build that ships out for the homework.

**Comment by pseeth** [comment]
Cool, thanks! Does it mimic librosa duration/offset arguments?

**Comment by ethman** [comment]
Yeah, it will mimic librosa. I've rearranged some of the logic so that nussl will raise an exception if there's an issue, because librosa will silently fail. I'm sure librosa's way of handling this is more "pythonic", but as a user I'd rather know where and when I've configured something wrong instead of trying to parse a stack trace from 4-5 lines after the actual error.
